### ISSUE TITLE
Analysisssss Reaction Submit Form - request for a recoil proton by default, and a warning if it is missing

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/MCwrapperFE#1]
I am making this request for the Analysis Reaction Submit form in MCWrapper AND in the Analysis Launch Submit Reaction form (which is even more important than MCW due to the amount of data involved).  A couple of times I forgot to include the recoil proton in the requested reaction - clearly a silly user error, but the naming convention for the reaction trees omits the proton and so makes it easy to forget here - and the disastrous example was for the analysis tree request, where it takes months to get the mistake corrected.  It's a silly mistake, but it's costly, and I know I'm not the only person who has done this. 

Please could you prefill the first of the output particles as a proton by default, and also have the button 'Include in list of reactions' check to see if it is present and print a reminder if it is missing?     

One could imagine adding in lepton and baryon number conservation but I'm just asking for the simplest fix in the hope that it'll be done before someone makes the same mistake again.   Thank you!

**Comment by T-Britton** [comment]
sorry I missed this! (I didn't have it watched properly!)

I think this should be fairly easily doable (the proton thing).  I thought about the conservation things but the complexity started to grow.  Definitely should be possible to include but with more effort. I'll try to take a look at doing this on the MCWrapper side soon and pass along the changes to Alex A for the Analysisssss form (they are the same)

**Comment by T-Britton** [comment]
done and live.  I have passed along the modifications (two trivial modifications)
