### ISSUE TITLE
Prefill puts jana.config in wrong box

### ISSUE THREAD

**Issue by s6pepaul** [JeffersonLab/MCwrapperFE#2]
If one tries copying a job to prefill the form where the old job used a jana.config file (e.g. https://halldweb.jlab.org/gluex_sim/SubmitSim.html?mod=2&prefill=2355). it looks like the copied version puts the jana.config file into a ReactionFilter box instead.

(reported by Jon, posted on his behalf)

**Comment by T-Britton** [comment]
fixed.  There may be other projects caught in this insert bug (fixed awhile ago).  We'll fix as needed
