### ISSUE TITLE
The version dropdown menus are empty

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/MCwrapperFE#3]
![image](https://user-images.githubusercontent.com/15655254/155852568-f227d42b-798e-4fc1-b88b-f05aabae9b2c.png)

**Comment by nsjarvis** [comment]
( Screenshot from https://halldweb.jlab.org/gluex_sim/SubmitSim.html )

**Comment by T-Britton** [comment]
There was an issue with build scripts crawler. I thought we had permanently fixed it yesterday. As soon as I get the log files I’ll get it back up. In an hour or so I’ll reimplement the temporary patch and get it repopulated

Thomas Britton

On Feb 26, 2022, at 12:19 PM, nsjarvis ***@***.***> wrote:

﻿

( Screenshot from https://halldweb.jlab.org/gluex_sim/SubmitSim.html )

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JeffersonLab_MCwrapperFE_issues_3-23issuecomment-2D1052338822&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=ccFffx721N71hPpKcJGvJIqY9RM4gBTuzp9ir7rze5Q&m=KVVVJZpc9ltFcbgQ7KNhUuVdV3HgWzRN6AOXk9V1ymQfZe66i2rw2brjMnnRpyx1&s=rZi3rtBrIQCZIdirA8j2glY9igN994JjAK6tOpjQuF4&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFRO2BDSTOI64QJT64MMEPLU5EDSZANCNFSM5PNI2TJA&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=ccFffx721N71hPpKcJGvJIqY9RM4gBTuzp9ir7rze5Q&m=KVVVJZpc9ltFcbgQ7KNhUuVdV3HgWzRN6AOXk9V1ymQfZe66i2rw2brjMnnRpyx1&s=4FlzlGgJDWUml0-CEtB80Avk_LBG_iC1Ikp-Wfh_WKg&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=ccFffx721N71hPpKcJGvJIqY9RM4gBTuzp9ir7rze5Q&m=KVVVJZpc9ltFcbgQ7KNhUuVdV3HgWzRN6AOXk9V1ymQfZe66i2rw2brjMnnRpyx1&s=QAq-94sx9VQk6nhKF3IKk9j5gzhxb3HTPmOoM71zQZ8&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=ccFffx721N71hPpKcJGvJIqY9RM4gBTuzp9ir7rze5Q&m=KVVVJZpc9ltFcbgQ7KNhUuVdV3HgWzRN6AOXk9V1ymQfZe66i2rw2brjMnnRpyx1&s=wjy8aB4xvJsgGghtRhPlo92hc2kAjLgpZFnp5J7UhCc&e=>.

**Comment by T-Britton** [comment]
should be fixed
